spring:
  security:
    oauth2:
      client:
        registration:
          google:
            scope: profile,email
          kakao:
            authorization-grant-type: authorization_code
            redirect-uri: 'https://signs.hoteldelluna.com/login/oauth2/code/{registrationId}'
            scope: account_email
            client-authentication-method: client_secret_post
          naver:
            authorization-grant-type: authorization_code
            redirect-uri: 'https://signs.hoteldelluna.com/login/oauth2/code/{registrationId}'
            scope: name,email,profile_image
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    root: DEBUG
    jdk:
      event:
        security: INFO
    com:
      zaxxer: INFO
    org:
      hibernate: INFO
      springframework:
        boot: INFO
        beans: INFO
        context:
          annotation: INFO
        web:
          servlet: ERROR
        orm:
          jpa:
            support: INFO
            apache:
            coyote: INFO
            tomcat: INFO
            catalina:
            authenticator: INFO
            connector:
             CoyoteAdapter: INFO
          session:
            ManagerBase: INFO
          realm:
            RealmBase: INFO
